# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- features/*

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'Npm install and build'

- task: CopyFiles@2
  displayName: Copy Files
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
     **/*
     !.git/**/*
     !node_modules
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

# - task: CopyFiles@2
#   displayName: Copy Files
#   inputs:
#     SourceFolder: '$(Build.SourcesDirectory)'
#     Contents: |
#      **/*
#      !.git/**/*
#     TargetFolder: $(Build.ArtifactStagingDirectory)

# - task: CopyFiles@2
#   inputs:
#     targetFolder: '$(Build.ArtifactStagingDirectory)'

# - task: PublishBuildArtifacts@1
#   displayName: Publish Build Artifacts
#   inputs:
#     pathtoPublish: $(Build.ArtifactStagingDirectory)
#     artifactName: MyBuildOutputs
    
